### PR TITLE
Fix constructing url paths

### LINKED ISSUE #272: Error 403 on assets when rootPath is "/"
Hello,

So I have a problem with AdminBro, everything is working perfectly but If I try to set rootPath to "/", It loads but without any assets (no css, no js). He is trying to making every request without the domain name like "http://frontend/assets/icomoon.css"

Network tab of Chrome DevTools:

Tried on localhost, tried on production = same result.
Tried in a new project with only express & adminbro = same result.

Here is a snippet to reproduce the error (the same as the one in Get Started page)

```javascript
const AdminBro = require('admin-bro')
const AdminBroExpress = require('admin-bro-expressjs')

const express = require('express')
const app = express()

const adminBro = new AdminBro({
  databases: [],
  rootPath: '/',
})

const router = AdminBroExpress.buildRouter(adminBro)

app.use(adminBro.options.rootPath, router)
app.listen(8080, () => console.log('AdminBro is under localhost:8080/admin'))
```

package.json

```json
{
    "admin-bro": "^1.6.0",
    "admin-bro-expressjs": "^0.4.0",
}
```

Thanks

### PR DESCRIPTION
**Pull request by JonaszJestem**
Fixed constructing invalid paths like `//frontend/[...]` by using `path.join()`

Resolves #272

### CODE REVIEW

File: src/admin-bro.ts [hunk 1]
```diff
@@ -178,7 +178,7 @@ class AdminBro {
      */
     this.options = _.merge({}, defaults, options)
 
-    const defaultLogo = `${this.options.rootPath}/frontend/assets/logo-mini.svg`
+    const defaultLogo = path.join(this.options.rootPath, '/frontend/assets/logo-mini.svg')
```
Comment (wojtek-krysiak) [inline src/admin-bro.ts]: not sure but it can break on windows machines where path returns "\" instead of "/".

Do you have an option to test it on windows?

if it breakes you can use slash (which is in deps already) (`import slash from 'slash'`)

**Comment by piotrwilczynski88** [comment]
# [Codecov](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348?src=pr&el=h1) Report
> Merging [#348](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348?src=pr&el=desc) into [master](https://codecov.io/gh/SoftwareBrothers/admin-bro/commit/9d9a30642419a16f5771615183332c9d8cb44ad7&el=desc) will **decrease** coverage by `0.27%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #348      +/-   ##
==========================================
- Coverage   58.33%   58.06%   -0.28%     
==========================================
  Files         237      237              
  Lines        3809     3815       +6     
  Branches      566      567       +1     
==========================================
- Hits         2222     2215       -7     
- Misses       1468     1480      +12     
- Partials      119      120       +1     
```


| [Impacted Files](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/backend/decorators/resource-decorator.ts](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348/diff?src=pr&el=tree#diff-c3JjL2JhY2tlbmQvZGVjb3JhdG9ycy9yZXNvdXJjZS1kZWNvcmF0b3IudHM=) | `77.77% <0.00%> (-11.12%)` | :arrow_down: |
| [src/backend/decorators/action-decorator.ts](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348/diff?src=pr&el=tree#diff-c3JjL2JhY2tlbmQvZGVjb3JhdG9ycy9hY3Rpb24tZGVjb3JhdG9yLnRz) | `75.75% <0.00%> (-6.07%)` | :arrow_down: |
| [src/backend/utils/view-helpers.ts](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348/diff?src=pr&el=tree#diff-c3JjL2JhY2tlbmQvdXRpbHMvdmlldy1oZWxwZXJzLnRz) | `58.82% <0.00%> (+0.20%)` | :arrow_up: |
| [src/frontend/store/store.ts](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348/diff?src=pr&el=tree#diff-c3JjL2Zyb250ZW5kL3N0b3JlL3N0b3JlLnRz) | `91.13% <0.00%> (ø)` | |
| [src/frontend/components/property-type/index.tsx](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348/diff?src=pr&el=tree#diff-c3JjL2Zyb250ZW5kL2NvbXBvbmVudHMvcHJvcGVydHktdHlwZS9pbmRleC50c3g=) | `59.64% <0.00%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348?src=pr&el=footer). Last update [9d9a306...6d42ba4](https://codecov.io/gh/SoftwareBrothers/admin-bro/pull/348?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).
